#!/bin/bash
# GUIA RÁPIDO - Configuração Inicial do Gerador CNAB 240

echo "=========================================="
echo "GERADOR CNAB 240 - CONFIGURAÇÃO INICIAL"
echo "=========================================="
echo ""

# Criar estrutura de diretórios
echo "1. Criando estrutura de diretórios..."
mkdir -p configs_bancos
mkdir -p remessas
mkdir -p exemplos
echo "   ✓ Diretórios criados"
echo ""

# Copiar template de configuração
echo "2. Criando template de configuração do banco..."
if [ ! -f "configs_bancos/TEMPLATE.json" ]; then
    cp config_cnab240_exemplo.json configs_bancos/TEMPLATE.json
    echo "   ✓ Template copiado para configs_bancos/TEMPLATE.json"
else
    echo "   ⚠ Template já existe"
fi
echo ""

echo "=========================================="
echo "PRÓXIMOS PASSOS:"
echo "=========================================="
echo ""
echo "1. Configure seu banco:"
echo "   cd configs_bancos/"
echo "   cp TEMPLATE.json meu_banco.json"
echo "   # Edite meu_banco.json com os dados do seu banco"
echo ""
echo "2. Prepare seus arquivos CSV:"
echo "   - contas_pagar.csv (suas contas a pagar)"
echo "   - correlacao_banco.csv (centro custo → banco)"
echo "   - relatorios/pessoas_cadastradas.csv (dados das pessoas)"
echo ""
echo "   Exemplos disponíveis em: exemplos/"
echo ""
echo "3. Execute o processador:"
echo "   python processar_contas_pagar_cnab.py \\"
echo "       contas_pagar.csv \\"
echo "       correlacao_banco.csv \\"
echo "       relatorios/pessoas_cadastradas.csv \\"
echo "       configs_bancos/"
echo ""
echo "4. Verifique os arquivos gerados em: remessas/"
echo ""
echo "=========================================="
echo "DOCUMENTAÇÃO COMPLETA:"
echo "=========================================="
echo ""
echo "- README_CNAB240.md - Guia completo de uso"
echo "- DOCUMENTACAO_COMPLETA_CNAB240.md - Documentação técnica"
echo "- config_cnab240_schema.json - Schema de configuração"
echo ""
echo "=========================================="
echo "CAMPOS IMPORTANTES DO BANCO:"
echo "=========================================="
echo ""
echo "Você precisará consultar o manual CNAB 240 do seu banco para:"
echo ""
echo "✓ Código do banco (3 dígitos)"
echo "   Ex: 237 (Bradesco), 341 (Itaú), 001 (BB)"
echo ""
echo "✓ Versões de layout"
echo "   - versao_layout_lote (ex: '045')"
echo "   - versao_layout_arquivo (ex: '103')"
echo ""
echo "✓ Formas de lançamento"
echo "   - forma_lancamento_credito (ex: '01')"
echo "   - forma_lancamento_ted (ex: '41')"
echo "   - forma_lancamento_pix_chave (ex: '45')"
echo "   - forma_lancamento_pix_qr (ex: '47')"
echo ""
echo "✓ Câmaras centralizadoras"
echo "   - camara_centralizadora_credito (ex: '000')"
echo "   - camara_centralizadora_pix (ex: '009')"
echo ""
echo "=========================================="
echo "IMPORTANTE:"
echo "=========================================="
echo ""
echo "⚠ SEMPRE teste os arquivos gerados em ambiente de"
echo "  HOMOLOGAÇÃO do banco antes de usar em produção!"
echo ""
echo "⚠ Verifique MANUALMENTE os totalizadores no"
echo "  relatório de validação (arquivo .json)"
echo ""
echo "⚠ Mantenha BACKUP dos arquivos de configuração"
echo ""
echo "=========================================="
echo "Configuração inicial concluída!"
echo "=========================================="
